// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJ28XxegHbYLpumAe6llTme91oJ8mdt4',
    appId: '1:836992483551:web:c59d6c42561d80fc5e296a',
    messagingSenderId: '836992483551',
    projectId: 'quedamos-backend',
    authDomain: 'quedamos-backend.firebaseapp.com',
    storageBucket: 'quedamos-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrz9qllAjyYVGCZmdVM7O2e3gHOuG6oh4',
    appId: '1:836992483551:ios:8613fee480765f775e296a',
    messagingSenderId: '836992483551',
    projectId: 'quedamos-backend',
    storageBucket: 'quedamos-backend.firebasestorage.app',
    iosBundleId: 'com.example.quedamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrz9qllAjyYVGCZmdVM7O2e3gHOuG6oh4',
    appId: '1:836992483551:ios:8613fee480765f775e296a',
    messagingSenderId: '836992483551',
    projectId: 'quedamos-backend',
    storageBucket: 'quedamos-backend.firebasestorage.app',
    iosBundleId: 'com.example.quedamos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJ28XxegHbYLpumAe6llTme91oJ8mdt4',
    appId: '1:836992483551:web:730b0b7fb2ee28ae5e296a',
    messagingSenderId: '836992483551',
    projectId: 'quedamos-backend',
    authDomain: 'quedamos-backend.firebaseapp.com',
    storageBucket: 'quedamos-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zWOmJwHEXuutcunfE1E5-NC4CGBT80o',
    appId: '1:836992483551:android:89581d4a7234ff465e296a',
    messagingSenderId: '836992483551',
    projectId: 'quedamos-backend',
    storageBucket: 'quedamos-backend.firebasestorage.app',
  );

}