import 'package:flutter/material.dart';
import '../app_colors.dart';

final Map<String, IconData> iconosMap = {
  "event": Icons.event,
  "star": Icons.star,
  "home": Icons.home,
  "work": Icons.work,
  "favorite": Icons.favorite,
  "school": Icons.school,
  "shopping": Icons.shopping_cart,
  "restaurant": Icons.restaurant,
  "fitness": Icons.fitness_center,
  "travel": Icons.flight,
  "music": Icons.music_note,
  "movie": Icons.movie,
  "pets": Icons.pets,
  "beach": Icons.beach_access,
  "birthday": Icons.cake,
  "meeting": Icons.meeting_room,
  "coffee": Icons.coffee,
  "book": Icons.book,
  "camera": Icons.camera_alt,
};

final Map<String, Color> coloresMap = {
  "red": Colors.red,
  "pink": Colors.pink,
  "purple": Colors.purple,
  "deepPurple": Colors.deepPurple,
  "indigo": Colors.indigo,
  "blue": Colors.blue,
  "lightBlue": Colors.lightBlue,
  "cyan": Colors.cyan,
  "teal": Colors.teal,
  "green": Colors.green,
  "lightGreen": Colors.lightGreen,
  "lime": Colors.lime,
  "yellow": Colors.yellow,
  "amber": Colors.amber,
  "orange": Colors.orange,
  "deepOrange": Colors.deepOrange,
  "brown": Colors.brown,
  "grey": Colors.grey,
  "blueGrey": Colors.blueGrey,
  "secondary": secondary,
};